import { StyleSheet, Platform } from 'react-native';
import { ThemeColors } from '../../../utils/colors';
import { scale, verticalScale, fontSize, spacing } from '../../../utils/responsive';

export const createStyles = (theme: ThemeColors) => {
  const isDark = theme.HEADER_BACKGROUND === '#0F1012';
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.BACKGROUND,
      paddingTop: verticalScale(40),
    },
    scrollContent: {
      flexGrow: 1,
      paddingHorizontal: spacing(16),
      paddingTop: verticalScale(20),
      paddingBottom: verticalScale(48),
    },
    stepDots: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      gap: spacing(10),
      marginBottom: verticalScale(28),
    },
    stepDot: {
      width: scale(8),
      height: scale(8),
      borderRadius: scale(4),
    },
    stepDotActive: {
      width: scale(24),
      borderRadius: scale(12),
    },
    card: {
      backgroundColor: theme.BACKGROUND_LIGHT,
      borderRadius: scale(28),
      padding: spacing(32),
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: isDark ? 'rgba(198, 165, 107, 0.15)' : 'rgba(198, 165, 107, 0.12)',
      ...Platform.select({
        ios: {
          shadowColor: isDark ? '#000' : theme.PRIMARY,
          shadowOffset: { width: 0, height: 12 },
          shadowOpacity: isDark ? 0.35 : 0.08,
          shadowRadius: 28,
        },
        android: { elevation: 12 },
      }),
    },
    cardInner: {
      alignItems: 'center',
    },
    iconRing: {
      width: scale(96),
      height: scale(96),
      borderRadius: scale(48),
      justifyContent: 'center',
      alignItems: 'center',
      alignSelf: 'center',
      marginBottom: spacing(28),
      borderWidth: 2,
      borderColor: theme.SECONDARY + '40',
      backgroundColor: theme.SECONDARY + '12',
      ...Platform.select({
        ios: {
          shadowColor: theme.SECONDARY,
          shadowOffset: { width: 0, height: 0 },
          shadowOpacity: 0.25,
          shadowRadius: 20,
        },
        android: { elevation: 8 },
      }),
    },
    iconWrapper: {
      justifyContent: 'center',
      alignItems: 'center',
    },
    title: {
      fontSize: fontSize(28),
      fontWeight: '800',
      color: theme.TEXT,
      textAlign: 'center',
      marginBottom: spacing(12),
      letterSpacing: -0.5,
    },
    subtitle: {
      fontSize: fontSize(16),
      color: theme.LIGHT_TEXT,
      textAlign: 'center',
      marginBottom: spacing(32),
      lineHeight: fontSize(24),
      paddingHorizontal: spacing(8),
      opacity: 0.95,
    },
    emailHint: {
      fontSize: fontSize(14),
      color: theme.SECONDARY,
      textAlign: 'center',
      marginBottom: spacing(20),
      fontWeight: '600',
      letterSpacing: 0.3,
    },
    inputWrap: {
      width: '100%',
      marginBottom: spacing(20),
    },
    termsRow: {
      flexDirection: 'row',
      alignItems: 'center',
      alignSelf: 'flex-start',
      marginBottom: spacing(20),
      paddingVertical: spacing(4),
    },
    checkboxTouch: {
      marginRight: spacing(12),
    },
    checkbox: {
      width: scale(24),
      height: scale(24),
      borderRadius: scale(6),
      borderWidth: 2,
      borderColor: theme.BORDER_COLOR,
      justifyContent: 'center',
      alignItems: 'center',
    },
    checkboxChecked: {
      backgroundColor: theme.SECONDARY,
      borderColor: theme.SECONDARY,
    },
    termsLabel: {
      fontSize: fontSize(14),
      color: theme.LIGHT_TEXT,
      flex: 1,
    },
    termsLink: {
      color: theme.SECONDARY,
      fontWeight: '700',
      textDecorationLine: 'underline',
    },
    codeInputRow: {
      flexDirection: 'row',
      justifyContent: 'center',
      gap: spacing(10),
      marginBottom: spacing(28),
    },
    codeBox: {
      width: scale(48),
      height: scale(56),
      borderRadius: scale(14),
      backgroundColor: theme.INPUT_BACKGROUND,
      borderWidth: 2,
      borderColor: theme.BORDER_COLOR,
      justifyContent: 'center',
      alignItems: 'center',
    },
    codeBoxFilled: {
      borderColor: theme.SECONDARY + '80',
      backgroundColor: theme.SECONDARY + '08',
    },
    codeBoxText: {
      fontSize: fontSize(26),
      fontWeight: '800',
      color: theme.TEXT,
      letterSpacing: 0,
    },
    codeInput: {
      backgroundColor: theme.INPUT_BACKGROUND,
      borderRadius: scale(20),
      paddingHorizontal: spacing(28),
      paddingVertical: verticalScale(28),
      minWidth: '100%',
      minHeight: verticalScale(72),
      fontSize: fontSize(32),
      fontWeight: '700',
      color: theme.TEXT,
      textAlign: 'center',
      letterSpacing: 14,
      borderWidth: 2,
      borderColor: theme.BORDER_COLOR,
    },
    codeInputWrapper: {
      marginBottom: spacing(28),
    },
    primaryButton: {
      width: '100%',
      borderRadius: scale(16),
      paddingVertical: spacing(18),
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: spacing(8),
      overflow: 'hidden',
      minHeight: scale(56),
      borderWidth: 1,
      borderColor: theme.SECONDARY + '50',
      ...Platform.select({
        ios: {
          shadowColor: theme.SECONDARY,
          shadowOffset: { width: 0, height: 4 },
          shadowOpacity: 0.2,
          shadowRadius: 12,
        },
        android: { elevation: 4 },
      }),
    },
    primaryButtonInner: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: spacing(10),
    },
    primaryButtonText: {
      fontSize: fontSize(17),
      fontWeight: '700',
      color: theme.PRIMARY,
      letterSpacing: 0.3,
    },
    resendBtn: {
      alignSelf: 'center',
      marginTop: spacing(24),
      paddingVertical: spacing(10),
      paddingHorizontal: spacing(16),
    },
    resendText: {
      fontSize: fontSize(15),
      color: theme.SECONDARY,
      fontWeight: '600',
      letterSpacing: 0.2,
    },
    backBtn: {
      alignSelf: 'center',
      marginTop: spacing(14),
      paddingVertical: spacing(10),
      paddingHorizontal: spacing(16),
    },
    backText: {
      fontSize: fontSize(14),
      color: theme.LIGHT_TEXT,
      fontWeight: '600',
      letterSpacing: 0.2,
      opacity: 0.9,
    },
    divider: {
      height: 1,
      backgroundColor: theme.BORDER_COLOR,
      marginVertical: spacing(24),
      opacity: 0.6,
    },
  });
};
