import { StyleSheet, Platform } from 'react-native';
import { ThemeColors } from '../../utils/colors';
import { scale, fontSize, spacing, verticalScale } from '../../utils/responsive';

export const createStyles = (theme: ThemeColors) => {
  const isDark = theme.HEADER_BACKGROUND === '#0F1012';
  const plateBg = isDark ? '#1B1B20' : theme.BACKGROUND_LIGHT;
  const ink = theme.TEXT;
  const muted = theme.LIGHT_TEXT;
  const gold = theme.SECONDARY;

  return StyleSheet.create({
    // —— Shared forged shell ——
    forgedOuter: {
      borderRadius: scale(22),
      padding: scale(2),
      marginBottom: spacing(12),
      width: '100%',
      ...Platform.select({
        ios: {
          shadowColor: '#000',
          shadowOffset: { width: 0, height: 10 },
          shadowOpacity: isDark ? 0.45 : 0.12,
          shadowRadius: 22,
        },
        android: { elevation: 8 },
      }),
    },
    forgedOuterGrid: {
      marginBottom: 0,
      borderRadius: scale(20),
      padding: scale(2),
      flex: 1,
      width: '100%',
      ...Platform.select({
        ios: {
          shadowColor: '#000',
          shadowOffset: { width: 0, height: 8 },
          shadowOpacity: isDark ? 0.4 : 0.1,
          shadowRadius: 16,
        },
        android: { elevation: 6 },
      }),
    },
    forgedPlate: {
      borderRadius: scale(20),
      overflow: 'hidden',
      backgroundColor: plateBg,
      position: 'relative',
    },
    forgedPlateGrid: {
      borderRadius: scale(18),
      overflow: 'hidden',
      backgroundColor: plateBg,
      position: 'relative',
      minHeight: verticalScale(158),
    },
    vignette: {
      ...StyleSheet.absoluteFillObject,
    },
    bracketTL: {
      position: 'absolute',
      top: spacing(10),
      left: spacing(10),
      width: scale(18),
      height: scale(18),
      borderTopWidth: 2,
      borderLeftWidth: 2,
      borderColor: gold,
      opacity: 0.85,
      zIndex: 4,
    },
    bracketBR: {
      position: 'absolute',
      bottom: spacing(10),
      right: scale(52),
      width: scale(18),
      height: scale(18),
      borderBottomWidth: 2,
      borderRightWidth: 2,
      borderColor: gold,
      opacity: 0.85,
      zIndex: 4,
    },
    bracketTRGrid: {
      position: 'absolute',
      top: spacing(8),
      right: spacing(8),
      width: scale(14),
      height: scale(14),
      borderTopWidth: 1.5,
      borderRightWidth: 1.5,
      borderColor: gold,
      opacity: 0.75,
      zIndex: 4,
    },
    bracketBLGrid: {
      position: 'absolute',
      bottom: spacing(8),
      left: spacing(8),
      width: scale(14),
      height: scale(14),
      borderBottomWidth: 1.5,
      borderLeftWidth: 1.5,
      borderColor: gold,
      opacity: 0.75,
      zIndex: 4,
    },
    sharedForged: {
      ...Platform.select({
        ios: {
          shadowColor: gold,
          shadowOffset: { width: 0, height: 0 },
          shadowOpacity: 0.35,
          shadowRadius: 12,
        },
        android: { elevation: 9 },
      }),
    },

    // —— List row ——
    listRow: {
      flexDirection: 'row',
      alignItems: 'stretch',
      minHeight: verticalScale(92),
    },
    prismSlot: {
      width: scale(26),
      overflow: 'hidden',
      marginLeft: spacing(4),
    },
    prism: {
      flex: 1,
      marginHorizontal: -scale(8),
      transform: [{ skewX: '-14deg' }],
    },
    perfCol: {
      width: scale(6),
      justifyContent: 'space-evenly',
      alignItems: 'center',
      paddingVertical: spacing(14),
      marginLeft: spacing(2),
    },
    perfDot: {
      width: scale(3),
      height: scale(3),
      borderRadius: scale(2),
      opacity: 0.35,
    },
    iconSealOuter: {
      alignSelf: 'center',
      marginLeft: spacing(8),
      padding: scale(2),
      borderRadius: scale(18),
    },
    iconSealInner: {
      width: scale(56),
      height: scale(56),
      borderRadius: scale(16),
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: StyleSheet.hairlineWidth * 2,
      backgroundColor: isDark ? '#141418' : '#FAFAFA',
    },
    listBody: {
      flex: 1,
      paddingLeft: spacing(14),
      paddingRight: spacing(8),
      paddingVertical: spacing(14),
      justifyContent: 'center',
      minWidth: 0,
    },
    vaultCatalog: {
      fontSize: fontSize(9),
      fontWeight: '800',
      letterSpacing: 1.8,
      color: gold,
      opacity: 0.95,
    },
    vaultCatalogShrink: {
      flex: 1,
      minWidth: 0,
      marginRight: spacing(10),
    },
    listTitle: {
      fontSize: fontSize(17),
      fontWeight: '900',
      letterSpacing: -0.4,
      color: ink,
      marginBottom: spacing(8),
      lineHeight: fontSize(22),
    },
    listMetaRow: {
      flexDirection: 'row',
      alignItems: 'center',
      flexWrap: 'wrap',
      gap: spacing(8),
    },
    listStat: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: verticalScale(5),
      paddingHorizontal: spacing(10),
      borderRadius: scale(8),
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: isDark ? 'rgba(198,165,107,0.22)' : 'rgba(198,165,107,0.35)',
      backgroundColor: isDark ? 'rgba(198,165,107,0.06)' : 'rgba(198,165,107,0.08)',
    },
    listStatText: {
      marginLeft: spacing(6),
      fontSize: fontSize(12),
      fontWeight: '700',
      color: muted,
      letterSpacing: 0.3,
    },
    listShared: {
      marginTop: spacing(6),
      fontSize: fontSize(11),
      fontWeight: '700',
      color: gold,
      letterSpacing: 0.2,
    },
    listTopActions: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: spacing(4),
    },
    listEdit: {
      width: scale(44),
      height: scale(44),
      borderRadius: scale(13),
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: isDark ? 'rgba(255,255,255,0.1)' : 'rgba(15,16,20,0.1)',
      backgroundColor: isDark ? 'rgba(0,0,0,0.45)' : 'rgba(255,255,255,0.82)',
      ...Platform.select({
        ios: {
          shadowColor: '#000',
          shadowOffset: { width: 0, height: 1 },
          shadowOpacity: isDark ? 0.35 : 0.07,
          shadowRadius: 2,
        },
        android: { elevation: 1 },
      }),
    },
    ingotRail: {
      width: scale(46),
      alignSelf: 'stretch',
      justifyContent: 'center',
      alignItems: 'center',
      paddingVertical: spacing(8),
      borderLeftWidth: StyleSheet.hairlineWidth,
      borderLeftColor: isDark ? 'rgba(198,165,107,0.2)' : 'rgba(198,165,107,0.35)',
    },
    ingotSerial: {
      marginTop: spacing(8),
      fontSize: fontSize(10),
      fontWeight: '900',
      letterSpacing: 2,
      color: isDark ? 'rgba(26,26,30,0.95)' : 'rgba(255,255,255,0.95)',
      opacity: 0.9,
    },
    shineSweep: {
      ...StyleSheet.absoluteFillObject,
    },

    // —— Grid tile ——
    gridIngotBar: {
      height: verticalScale(7),
      width: '100%',
    },
    gridNotchRow: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      gap: spacing(5),
      paddingTop: spacing(10),
      paddingBottom: spacing(4),
    },
    gridNotchDot: {
      width: scale(4),
      height: scale(4),
      borderRadius: scale(2),
      opacity: 0.5,
    },
    gridSealWrap: {
      alignItems: 'center',
      marginTop: -verticalScale(18),
      marginBottom: spacing(4),
      zIndex: 3,
    },
    gridSealOuter: {
      padding: scale(3),
      borderRadius: scale(999),
    },
    gridSealInner: {
      width: scale(54),
      height: scale(54),
      borderRadius: scale(27),
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: StyleSheet.hairlineWidth * 2,
      backgroundColor: isDark ? '#121214' : '#FDFDFB',
    },
    gridSerialAbs: {
      position: 'absolute',
      top: spacing(10),
      right: spacing(12),
      zIndex: 5,
      fontSize: fontSize(9),
      fontWeight: '900',
      letterSpacing: 1.6,
      color: gold,
      opacity: 0.9,
    },
    gridBody: {
      paddingHorizontal: spacing(12),
      paddingBottom: spacing(12),
      minWidth: 0,
    },
    gridHeadRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: spacing(6),
    },
    gridTypeCaps: {
      fontSize: fontSize(9),
      fontWeight: '900',
      letterSpacing: 1.4,
    },
    gridSpacer: { flex: 1, minWidth: spacing(4) },
    gridEdit: {
      width: scale(40),
      height: scale(40),
      borderRadius: scale(12),
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: isDark ? 'rgba(255,255,255,0.1)' : 'rgba(15,16,20,0.1)',
      backgroundColor: isDark ? 'rgba(0,0,0,0.45)' : 'rgba(255,255,255,0.82)',
      ...Platform.select({
        ios: {
          shadowColor: '#000',
          shadowOffset: { width: 0, height: 1 },
          shadowOpacity: isDark ? 0.3 : 0.06,
          shadowRadius: 2,
        },
        android: { elevation: 1 },
      }),
    },
    gridTitle: {
      fontSize: fontSize(15),
      fontWeight: '900',
      letterSpacing: -0.32,
      color: ink,
      marginBottom: spacing(10),
      lineHeight: fontSize(20),
    },
    gridFoot: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: spacing(8),
    },
    gridStat: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
      minWidth: 0,
      paddingVertical: verticalScale(6),
      paddingHorizontal: spacing(8),
      borderRadius: scale(10),
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: isDark ? 'rgba(198,165,107,0.2)' : 'rgba(198,165,107,0.32)',
      backgroundColor: isDark ? 'rgba(198,165,107,0.05)' : 'rgba(198,165,107,0.07)',
    },
    gridStatTxt: {
      marginLeft: spacing(5),
      fontSize: fontSize(11),
      fontWeight: '700',
      color: muted,
      flexShrink: 1,
    },
    gridChevGold: {
      width: scale(32),
      height: scale(32),
      borderRadius: scale(16),
      overflow: 'hidden',
      alignItems: 'center',
      justifyContent: 'center',
    },
    gridShared: {
      marginTop: spacing(8),
      fontSize: fontSize(10),
      fontWeight: '700',
      color: gold,
    },
  });
};
