import { StyleSheet, Platform } from 'react-native';
import { useTheme } from '../../../utils/colors';
import { scale, verticalScale, fontSize, spacing } from '../../../utils/responsive';

export const createStyles = () => {
  const { theme, isDark } = useTheme();
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: theme.HEADER_BACKGROUND,
    },
    headerContainer: {
      paddingTop: Platform.OS === 'ios' ? '15%' : '10%',
      paddingHorizontal: spacing(20),
      paddingBottom: verticalScale(20),
      backgroundColor: theme.HEADER_BACKGROUND,
    },
    headerContent: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    headerTitleContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    headerText: {
      color: theme.SECONDARY,
      fontSize: 26,
      fontWeight: '800',
      letterSpacing: 0.5,
    },
    headerRightContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    bookCountBadge: {
      backgroundColor: theme.SECONDARY,
      borderRadius: 20,
      paddingHorizontal: 10,
      paddingVertical: 5,
      minWidth: 30,
      alignItems: 'center',
      justifyContent: 'center',
      ...Platform.select({
        ios: {
          shadowColor: theme.SECONDARY,
          shadowOffset: { width: 0, height: 4 },
          shadowOpacity: 0.3,
          shadowRadius: 8,
        },
        android: {
          elevation: 6,
        },
      }),
    },
    bookCountText: {
      color: theme.PURPLE,
      fontSize: 16,
      fontWeight: '800',
    },
    addButton: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: theme.SECONDARY,
      justifyContent: 'center',
      alignItems: 'center',
      ...Platform.select({
        ios: {
          shadowColor: theme.SECONDARY,
          shadowOffset: { width: 0, height: 4 },
          shadowOpacity: 0.3,
          shadowRadius: 8,
        },
        android: {
          elevation: 6,
        },
      }),
    },
    content: {
      flex: 1,
      backgroundColor: theme.BACKGROUND,
      borderTopLeftRadius: scale(32),
      borderTopRightRadius: scale(32),
      paddingTop: verticalScale(24),
      ...Platform.select({
        ios: {
          shadowColor: '#000',
          shadowOffset: { width: 0, height: -8 },
          shadowOpacity: 0.15,
          shadowRadius: 20,
        },
        android: {
          elevation: 15,
        },
      }),
    },
    helperRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing(10),
      marginHorizontal: spacing(16),
      marginBottom: spacing(14),
      paddingVertical: spacing(12),
      paddingHorizontal: spacing(14),
      borderRadius: scale(16),
      backgroundColor: theme.BACKGROUND_LIGHT,
      borderWidth: StyleSheet.hairlineWidth * 2,
      borderColor: theme.BORDER_COLOR,
      ...Platform.select({
        ios: {
          shadowColor: theme.SHADOW,
          shadowOffset: { width: 0, height: 4 },
          shadowOpacity: 0.08,
          shadowRadius: 10,
        },
        android: { elevation: 2 },
      }),
    },
    helperText: {
      flex: 1,
      fontSize: fontSize(13),
      lineHeight: fontSize(18),
      fontWeight: '500',
      color: theme.LIGHT_TEXT,
    },
    listContent: {
      paddingBottom: 100,
      paddingHorizontal: 16,
    },
    bookGridRow: {
      gap: spacing(10),
      marginBottom: spacing(10),
    },
    bookGridCell: {
      flex: 1,
      minWidth: 0,
    },
    separator: {
      height: 6,
    },
    listFooter: {
      height: 100,
    },
    emptyState: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingVertical: verticalScale(100),
      paddingHorizontal: spacing(40),
    },
    emptyIconContainer: {
      width: 140,
      height: 140,
      borderRadius: 70,
      backgroundColor: theme.BACKGROUND_LIGHT,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 32,
      ...Platform.select({
        ios: {
          shadowColor: theme.SHADOW,
          shadowOffset: { width: 0, height: 8 },
          shadowOpacity: 0.15,
          shadowRadius: 20,
        },
        android: {
          elevation: 8,
        },
      }),
    },
    emptyText: {
      fontSize: 22,
      fontWeight: '700',
      marginTop: 16,
      marginBottom: 8,
      textAlign: 'center',
      color: theme.TEXT,
      letterSpacing: 0.3,
    },
    emptySubText: {
      fontSize: 15,
      fontWeight: '400',
      textAlign: 'center',
      lineHeight: 22,
      opacity: 0.7,
      marginTop: 8,
    },
    modalContent: {
      paddingHorizontal: spacing(16),
      paddingTop: spacing(8),
      paddingBottom: spacing(8),
    },
    bookFormScrollContent: {
      paddingBottom: spacing(36),
      gap: spacing(16),
    },
    bookFormHeroOuter: {
      borderRadius: scale(24),
      padding: scale(2),
      marginBottom: spacing(2),
      overflow: 'hidden',
      ...Platform.select({
        ios: {
          shadowColor: '#000',
          shadowOffset: { width: 0, height: 8 },
          shadowOpacity: isDark ? 0.32 : 0.08,
          shadowRadius: 20,
        },
        android: { elevation: 6 },
      }),
    },
    bookFormHeroInner: {
      borderRadius: scale(22),
      paddingVertical: verticalScale(18),
      paddingHorizontal: spacing(18),
      overflow: 'hidden',
    },
    bookFormHeroTop: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: verticalScale(10),
    },
    bookFormHeroChip: {
      paddingHorizontal: spacing(12),
      paddingVertical: verticalScale(5),
      borderRadius: scale(20),
      overflow: 'hidden',
    },
    bookFormHeroChipText: {
      fontSize: fontSize(10),
      fontWeight: '800',
      letterSpacing: 1.6,
    },
    bookFormHeroCharCount: {
      fontSize: fontSize(11),
      fontWeight: '600',
      color: theme.LIGHT_TEXT,
      opacity: 0.85,
    },
    bookFormHeroTitle: {
      fontSize: fontSize(22),
      fontWeight: '800',
      color: theme.TEXT,
      letterSpacing: -0.4,
      marginBottom: verticalScale(4),
    },
    bookFormHeroSubtitle: {
      fontSize: fontSize(13),
      fontWeight: '500',
      color: theme.LIGHT_TEXT,
      lineHeight: fontSize(19),
      opacity: 0.92,
    },
    nameFieldHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: spacing(10),
    },
    inputFocused: {
      borderColor: theme.SECONDARY,
      borderWidth: 2,
    },
    formSectionOuter: {
      borderRadius: scale(24),
      padding: scale(2),
      marginBottom: spacing(4),
      ...Platform.select({
        ios: {
          shadowColor: '#000',
          shadowOffset: { width: 0, height: 8 },
          shadowOpacity: isDark ? 0.28 : 0.08,
          shadowRadius: 16,
        },
        android: { elevation: 5 },
      }),
    },
    formSectionInner: {
      backgroundColor: theme.BACKGROUND_LIGHT,
      borderRadius: scale(22),
      padding: spacing(20),
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: isDark ? 'rgba(198, 165, 107, 0.16)' : theme.BORDER_COLOR,
    },
    formSection: {
      backgroundColor: theme.BACKGROUND_LIGHT,
      borderRadius: scale(16),
      padding: spacing(14),
      marginBottom: spacing(12),
      borderWidth: StyleSheet.hairlineWidth * 2,
      borderColor: theme.BORDER_COLOR,
    },
    fieldLabel: {
      fontSize: fontSize(10),
      fontWeight: '800',
      color: theme.LIGHT_TEXT,
      letterSpacing: 1.2,
      textTransform: 'uppercase',
      marginBottom: spacing(12),
    },
    bookTypeSectionOuter: {
      borderRadius: scale(24),
      padding: scale(2),
      marginBottom: spacing(4),
      ...Platform.select({
        ios: {
          shadowColor: '#000',
          shadowOffset: { width: 0, height: 8 },
          shadowOpacity: isDark ? 0.28 : 0.08,
          shadowRadius: 16,
        },
        android: { elevation: 5 },
      }),
    },
    bookTypeSectionInner: {
      backgroundColor: theme.BACKGROUND_LIGHT,
      borderRadius: scale(22),
      padding: spacing(20),
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: isDark ? 'rgba(198, 165, 107, 0.16)' : theme.BORDER_COLOR,
    },
    bookTypeSection: {
      backgroundColor: theme.BACKGROUND_LIGHT,
      borderRadius: scale(16),
      padding: spacing(14),
      marginBottom: spacing(8),
      borderWidth: StyleSheet.hairlineWidth * 2,
      borderColor: theme.BORDER_COLOR,
    },
    input: {
      borderWidth: StyleSheet.hairlineWidth * 2,
      borderColor: theme.BORDER_COLOR,
      borderRadius: scale(20),
      paddingVertical: spacing(18),
      paddingHorizontal: spacing(18),
      marginBottom: 0,
      color: theme.TEXT,
      fontSize: fontSize(18),
      fontWeight: '600',
      letterSpacing: -0.2,
      backgroundColor: theme.INPUT_BACKGROUND,
      ...Platform.select({
        ios: {
          shadowColor: theme.SHADOW,
          shadowOffset: { width: 0, height: 2 },
          shadowOpacity: 0.06,
          shadowRadius: 8,
        },
        android: { elevation: 1 },
      }),
    },
    modalButtonContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: spacing(10),
      marginTop: spacing(8),
    },
    modalButtonPrimary: {
      flex: 1,
      borderRadius: scale(20),
      overflow: 'hidden',
      ...Platform.select({
        ios: {
          shadowColor: theme.SECONDARY,
          shadowOffset: { width: 0, height: 8 },
          shadowOpacity: 0.38,
          shadowRadius: 14,
        },
        android: { elevation: 7 },
      }),
    },
    modalButtonPrimaryInner: {
      paddingVertical: spacing(17),
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: verticalScale(54),
    },
    modalButton: {
      backgroundColor: theme.PURPLE,
      borderRadius: scale(20),
      paddingVertical: spacing(16),
      alignItems: 'center',
      flex: 1,
      justifyContent: 'center',
      minHeight: verticalScale(52),
    },
    deleteButton: {
      backgroundColor: 'transparent',
      borderRadius: scale(20),
      borderWidth: StyleSheet.hairlineWidth * 2,
      borderColor: theme.ERROR,
    },
    modalButtonText: {
      color: theme.NAVBAR_ACTIVE_TEXT,
      fontSize: fontSize(16),
      fontWeight: '800',
      letterSpacing: 0.3,
    },
    deleteButtonText: {
      color: theme.ERROR,
      fontSize: fontSize(15),
      fontWeight: '700',
    },
    bookTypeHeader: {
      fontSize: fontSize(11),
      fontWeight: '800',
      color: theme.TEXT,
      letterSpacing: 1.1,
      textTransform: 'uppercase',
      marginBottom: spacing(8),
    },
    bookTypeHelper: {
      fontSize: fontSize(12),
      color: theme.LIGHT_TEXT,
      marginBottom: spacing(14),
      lineHeight: fontSize(18),
      fontWeight: '500',
    },
    segmentTrack: {
      flexDirection: 'row',
      borderRadius: scale(20),
      padding: scale(4),
      backgroundColor: theme.INPUT_BACKGROUND,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: isDark ? 'rgba(255,255,255,0.08)' : theme.BORDER_COLOR,
      gap: scale(4),
      ...Platform.select({
        ios: {
          shadowColor: '#000',
          shadowOffset: { width: 0, height: 2 },
          shadowOpacity: isDark ? 0.2 : 0.04,
          shadowRadius: 8,
        },
        android: { elevation: 2 },
      }),
    },
    segmentCell: {
      flex: 1,
      borderRadius: scale(16),
      overflow: 'hidden',
      minHeight: verticalScale(56),
    },
    segmentGradientFill: {
      flex: 1,
      borderRadius: scale(16),
    },
    segmentCellInner: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: spacing(8),
      paddingVertical: verticalScale(14),
      paddingHorizontal: spacing(10),
    },
    segmentCellIdle: {
      backgroundColor: 'transparent',
    },
    segmentLabel: {
      fontSize: fontSize(15),
      fontWeight: '800',
      letterSpacing: -0.2,
      color: theme.TEXT,
    },
    segmentLabelMuted: {
      color: theme.LIGHT_TEXT,
      fontWeight: '700',
    },
    segmentLabelOnGold: {
      color: theme.NAVBAR_ACTIVE_TEXT,
    },
  });
};
