import { StyleSheet, Platform } from 'react-native';
import { ThemeColors } from '../../../utils/colors';
import { scale, verticalScale, fontSize, spacing } from '../../../utils/responsive';

export const createStyles = (theme: ThemeColors) => {
  const isDark = theme.HEADER_BACKGROUND === '#0F1012';

  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: theme.BACKGROUND,
    },
    scrollContent: {
      flexGrow: 1,
      paddingTop: verticalScale(24),
      paddingHorizontal: spacing(20),
      paddingBottom: verticalScale(120),
    },
    avatarSection: {
      alignItems: 'center',
      paddingVertical: verticalScale(20),
      marginBottom: verticalScale(8),
    },
    avatarWrapper: {
      position: 'relative',
      marginBottom: spacing(16),
    },
    avatar: {
      width: scale(96),
      height: scale(96),
      borderRadius: scale(48),
      backgroundColor: theme.SECONDARY,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 3,
      borderColor: isDark ? 'rgba(198, 165, 107, 0.4)' : 'rgba(198, 165, 107, 0.3)',
      ...Platform.select({
        ios: {
          shadowColor: isDark ? '#000' : theme.PURPLE,
          shadowOffset: { width: 0, height: 8 },
          shadowOpacity: 0.3,
          shadowRadius: 16,
        },
        android: { elevation: 8 },
      }),
    },
    avatarText: {
      fontSize: 40,
      color: isDark ? theme.PURPLE : theme.BACKGROUND,
      fontWeight: '800',
      letterSpacing: 1,
    },
    editAvatarButton: {
      position: 'absolute',
      bottom: 0,
      right: 0,
      width: 38,
      height: 38,
      borderRadius: 19,
      backgroundColor: theme.BACKGROUND_LIGHT,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 2,
      borderColor: theme.SECONDARY,
      ...Platform.select({
        ios: {
          shadowColor: '#000',
          shadowOffset: { width: 0, height: 4 },
          shadowOpacity: 0.25,
          shadowRadius: 8,
        },
        android: { elevation: 6 },
      }),
    },
    nameSection: {
      alignItems: 'center',
      gap: spacing(8),
    },
    userName: {
      fontSize: fontSize(22),
      fontWeight: '700',
      color: theme.TEXT,
      letterSpacing: 0.3,
      textAlign: 'center',
    },
    editButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: isDark ? 'rgba(198, 165, 107, 0.15)' : 'rgba(198, 165, 107, 0.12)',
      paddingHorizontal: spacing(18),
      paddingVertical: spacing(10),
      borderRadius: scale(20),
      marginTop: 4,
      borderWidth: 1,
      borderColor: 'rgba(198, 165, 107, 0.25)',
    },
    editButtonText: {
      fontSize: fontSize(13),
      fontWeight: '700',
      color: theme.SECONDARY,
      letterSpacing: 0.3,
    },
    card: {
      backgroundColor: theme.BACKGROUND_LIGHT,
      borderRadius: scale(24),
      marginBottom: verticalScale(18),
      padding: spacing(22),
      borderWidth: 1,
      borderColor: isDark ? 'rgba(255,255,255,0.06)' : 'rgba(0,0,0,0.04)',
      ...Platform.select({
        ios: {
          shadowColor: '#000',
          shadowOffset: { width: 0, height: 4 },
          shadowOpacity: isDark ? 0.25 : 0.06,
          shadowRadius: 20,
        },
        android: { elevation: 6 },
      }),
    },
    cardHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing(12),
      marginBottom: spacing(18),
      paddingBottom: spacing(16),
      borderBottomWidth: 1,
      borderBottomColor: theme.BORDER_COLOR + '40',
    },
    cardTitle: {
      fontSize: fontSize(18),
      fontWeight: '800',
      color: theme.TEXT,
      letterSpacing: 0.3,
    },
    infoSection: {
      gap: 0,
    },
    row: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: spacing(16),
      borderBottomWidth: 1,
      borderBottomColor: theme.BORDER_COLOR + '25',
    },
    iconContainer: {
      width: 44,
      height: 44,
      borderRadius: scale(12),
      backgroundColor: isDark ? 'rgba(198, 165, 107, 0.12)' : 'rgba(198, 165, 107, 0.08)',
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: spacing(16),
    },
    labelContainer: {
      flex: 1,
      gap: 4,
    },
    labelText: {
      fontSize: fontSize(11),
      fontWeight: '600',
      color: theme.LIGHT_TEXT,
      letterSpacing: 0.3,
      textTransform: 'uppercase',
    },
    valueText: {
      fontSize: fontSize(16),
      fontWeight: '700',
      color: theme.TEXT,
      letterSpacing: 0.2,
    },
    settingsSection: {
      gap: 0,
    },
    settingRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: spacing(16),
    },
    settingLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
      marginRight: spacing(14),
    },
    settingIconContainer: {
      width: 44,
      height: 44,
      borderRadius: scale(12),
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: spacing(16),
    },
    settingContent: {
      flex: 1,
      gap: 4,
    },
    settingLabel: {
      fontSize: fontSize(16),
      fontWeight: '700',
      color: theme.TEXT,
      letterSpacing: 0.2,
    },
    settingDescription: {
      fontSize: fontSize(12),
      fontWeight: '500',
      color: theme.LIGHT_TEXT,
      opacity: 0.85,
    },
    logoutButton: {
      marginTop: verticalScale(10),
      marginBottom: verticalScale(6),
      backgroundColor: theme.ERROR_LIGHT,
      borderRadius: scale(20),
      paddingVertical: spacing(18),
      borderWidth: 1,
      borderColor: 'rgba(212, 93, 93, 0.25)',
      ...Platform.select({
        ios: {
          shadowColor: theme.ERROR,
          shadowOffset: { width: 0, height: 4 },
          shadowOpacity: 0.15,
          shadowRadius: 12,
        },
        android: { elevation: 4 },
      }),
    },
    logoutButtonContent: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: spacing(12),
    },
    logoutButtonText: {
      fontSize: fontSize(16),
      fontWeight: '700',
      color: theme.ERROR,
      letterSpacing: 0.3,
    },
    bottomSpacer: {
      height: verticalScale(20),
    },
    statsContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-around',
      paddingVertical: spacing(12),
    },
    statItem: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
      justifyContent: 'center',
    },
    statIconContainer: {
      width: scale(52),
      height: scale(52),
      borderRadius: scale(14),
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: spacing(14),
    },
    statContent: {
      alignItems: 'flex-start',
    },
    statValue: {
      fontSize: fontSize(28),
      fontWeight: '800',
      color: theme.TEXT,
      letterSpacing: 0.5,
    },
    statLabel: {
      fontSize: fontSize(11),
      fontWeight: '600',
      color: theme.LIGHT_TEXT,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
      marginTop: 2,
    },
    statDivider: {
      width: 1,
      height: 52,
      backgroundColor: theme.BORDER_COLOR + '50',
      marginHorizontal: spacing(8),
    },
  });
};
